# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.jogatina.com/")
    self.driver.set_window_size(1039, 728)
    assert self.driver.find_element(By.LINK_TEXT, "Jogatina.com").text == "Jogatina.com"
    assert self.driver.find_element(By.CSS_SELECTOR, ".buraco-aberto").text == "Buraco\\\\nQuem não conhece o Buraco? Também chamado de canastra e biriba, este jogo dispensa comentários: a diversão é garantida!\\\\nAndroid - iPhone - iPad"
    assert self.driver.find_element(By.CSS_SELECTOR, ".bingo").text == "Bingo\\\\nDivirta-se com o Bingo Online do Jogatina. Jogue com até 4 cartelas, junte pontos de experiência e conquiste vários prêmios! Totalmente grátis!\\\\niPad"
    assert self.driver.find_element(By.CSS_SELECTOR, ".tranca").text == "Tranca\\\\nNa Tranca, a carta \\\"3\\\" é muito importante. As vermelhas valem 100 pontos e as pretas trancam o lixo. Pense bem antes de usá-las!\\\\nAndroid - iPhone - iPad"
    assert self.driver.find_element(By.CSS_SELECTOR, ".truco-paulista > a").text == "Truco\\\\nConhecido de Norte a Sul, o Truco tem milhares de fãs. Como o blefe é permitido, nem sempre a melhor carta vence."
    assert self.driver.find_element(By.CSS_SELECTOR, ".paciencia").text == "Paciência\\\\nIndicada para treinar a concentração, diminuir a ansiedade e elevar o raciocínio lógico. Jogue quantas vezes quiser!\\\\nAndroid - iPhone - iPad"
    assert self.driver.find_element(By.CSS_SELECTOR, ".poker > a").text == "Poker\\\\nSocialização e desafio: o Poker Texas Holdem é o jogo de cartas mais popular do mundo. As fichas são grátis e a diversão também!"
    self.driver.find_element(By.CSS_SELECTOR, ".js-btn-cadastro").click()
    self.driver.find_element(By.ID, "emailIn").click()
    self.driver.find_element(By.ID, "emailIn").send_keys("viniciustester@tester.com")
    self.driver.find_element(By.ID, "password-field").click()
    self.driver.find_element(By.ID, "password-field").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-laranja:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Ver meu Perfil").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".active").text == "Perfil"
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(6) > a").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".titulo--pagina").text == "Gerenciar Conta"
    self.driver.find_element(By.CSS_SELECTOR, "#perfil .btn").click()
    self.driver.switch_to.frame(2)
    self.driver.find_element(By.ID, "campo-new-city").click()
    self.driver.find_element(By.ID, "campo-new-city").click()
    self.driver.find_element(By.ID, "campo-new-city").send_keys("Cariacica")
    self.driver.find_element(By.ID, "campo-new-state").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2)").click()
    self.driver.find_element(By.ID, "campo-new-state").send_keys("ES")
    self.driver.find_element(By.ID, "country").click()
    dropdown = self.driver.find_element(By.ID, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'Brasil']").click()
    self.driver.find_element(By.ID, "mascGender").click()
    self.driver.find_element(By.ID, "birthday").click()
    self.driver.find_element(By.ID, "birthmonth").click()
    self.driver.find_element(By.ID, "birthyear").click()
    dropdown = self.driver.find_element(By.ID, "birthyear")
    dropdown.find_element(By.XPATH, "//option[. = '1988']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".md-btn").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "span").text == "Perfil alterado com sucesso"
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "cboxClose").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".opcoes--cadastro__descricao > label:nth-child(2)").text == "Cariacica"
    assert self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(6)").text == "Brasil"
    assert self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(9)").text == "Masculino"
    assert self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(11)").text == "03/04/1988"
    self.driver.close()
  
